### ISSUE TITLE
Missing HttpClient instance. Use method AddHttpClient to add new instance

### ISSUE THREAD

**Issue by TikyConte** [Solitea/IdokladSdk#177]
IdokladSdk.Exceptions.IdokladSdkException: 'Missing HttpClient instance. Use method AddHttpClient to add new instance.'

Dobry den,
po upgreade z 3.7 na 4.0 v DokladApiBuilder hlasy chybu z vasej DLL, referencie sa nemenili ziadne co pozeram akurat ste odobrali resrsharp, v com moze byt problem.

**Comment by TikyConte** [comment]
V predoslej verzsii problem standartne s referenciou na restsharp, co verzia to fatalny fail, koncim s vasim wrapperom....

**Comment by miroelk** [comment]
Dobrý deň,

do DokladApiBuilderu je potrebné vložiť vlastnú instanciu triedy HttpClient.
Príklad použitia je v testovacom projekte IdokladSdk.NetCore.TestApp

```c#
_api = new DokladApiBuilder("Test", "1.0")
      .AddClientCredentialsAuthentication(_clientId, _clientSecret)
      .AddHttpClient(httpClient)
      .Build();
```

Readme opravíme v priebehu dnešného dňa.
